# Generated by Django 6.1.1 on 2026-09-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('peak_score', models.FloatField()),
                ('label_type', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('file_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels',
                                                 to='geobench.filebatch')),
            ],
            options={
                'unique_together': {('file_batch', 'start_time', 'end_time')},
            },
        ),
    ]
