# Generated by Django 6.1.1 on 2026-09-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
