# Generated by Django 6.1.1 on 2026-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobench', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownevent',
            name='time_end',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
